version: "3.9"

services:
  # api:
  #   build: .
  #   command: poetry run uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
  #   volumes:
  #     - .:/code
  #   ports:
  #     - "8000:8000"
  #   depends_on:
  #     - mongo
  #   environment:
  #     - MONGO_URL=mongodb://mongo:27017

  mongo:
    image: mongo:6.0
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
